# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Fire Arts Center of Chicago
email: info@firearts.org
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
timezone: America/Chicago
# twitter_username: jekyllrb
# github_username: FireArtsCenter

# Build settings
source: src
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - yarn.lock
  - gulp/
  - gulpfile.js
  - gulpfile.babel.js
  - static/

gtm_id: GTM-5BNZSL

organization:
    name: Fire Arts Center of Chicago
    address: 1830 N Kostner
    city: Chicago
    state: IL
    zip: 60639
    phones:
        - 773.544.9908
        - 312.842.2027
    email: info@firearts.org

menu:
    -
      name: Home
      class: home
      url: /
      subpages:
        -
          name: About Us
          class: about
          url: /aboutus.html
        -
          name: Location
          class: location
          url: /location.html
        -
          name: Membership
          class: membership
          url: /membership.html
    -
      name: Classes
      class: classes
      url: /classes.html
      subpages:
        -
          name: Foundry
          class: foundry
          url: /foundry.html
        -
          name: Furniture
          class: furniture
          url: /furniture.html
        -
          name: Metal Sculpture
          class: metal-sculpture
          url: /msculpture.html
        -
          name: Stone
          class: stone
          url: /stone.html
        -
          name: Forging
          class: forging
          url: /forge.html
        -
          name: Figure Study
          class: figure
          url: /figure.html
        -
          name: Full Class List
          class: full-list
          url: /fulllist.html
    -
      name: Gallery
      class: gallery
      url: /gallery.html
      subpages:
        -
          class: vince
          url: /vince.html
          name: Vince Hawkins
        -
          class: bryce
          url: /bryce.html
          name: Bryce de Reynier
        -
          class: kristin
          url: /kristin.html
          name: Kristin Komorowski
        -
          class: jon
          url: /jon.html
          name: Jon Gruber
        -
          class: kristian
          url: /kristian.html
          name: Kristian Damholt
        -
          class: elisotelo
          url: /elisotelo.html
          name: Eli Sotelo
        -
          class: lamar
          url: /lamar.html
          name: Lamar Wilson
        -
          class: student
          url: /student.html
          name: Student Work
    -
      name: Events
      url: /events.html
      class: events
    -
      name: Links
      url: /links.html
      class: links
      subpages:
        -
          class: facartists
          url: /facartists.html
          name: Fire Arts Artists
        -
          class: chicagoart
          url: /chicagoart.html
          name: Chicago Art
    -
      name: Contact Us
      url: /contactus.html
      class: contact
    -
      name: Donate
      url: /donate.html
      class: donate
      subpages:
        -
          class: wishlist
          url: /wishlist.html
          name: Wish List
